In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('exports/movies.csv')
df

,movie_id,title,overview,poster_url,emotion,emotion_num,rating
0,1,우주전쟁,전설적인 동명 소설을 새롭게 재해석한 이번 작품은 거대한 침공의 서막을 알린다. 에...,https://image.tmdb.org/t/p/w500/yvirUYrva23Iud...,기쁨,1.0,4.24
1,2,F1 더 무비,한때 주목받는 유망주였지만 끔찍한 사고로 F1®에서 우승하지 못하고 한순간에 추락한...,https://image.tmdb.org/t/p/w500/idhIZtest5NCeu...,불안,6.0,7.79
2,3,슈퍼맨,"슈퍼맨은 오늘도 세계 곳곳의 위협에 맞서 싸우지만, 시민들의 반응은 극과 극으로 갈...",https://image.tmdb.org/t/p/w500/kCXGCEsDqjzWJV...,불안,6.0,7.60
3,4,미션 임파서블: 파이널 레코닝,디지털상의 모든 정보를 통제할 수 있는 사상 초유의 무기로 인해 전 세계 국가와 조...,https://image.tmdb.org/t/p/w500/5Zxdorl5TharlI...,불안,1.0,7.24
4,5,이니 미니,20세기 스튜디오에서 선사하는 ⟪이니 미니⟫는 십 대 시절 도주 운전을 맡았던 주인...,https://image.tmdb.org/t/p/w500/12Va3oO3oYUdOd...,슬픔,3.0,6.70
...,...,...,...,...,...,...,...
95,216,Sorority,A tale of seduction and mystery. A fearless pr...,https://image.tmdb.org/t/p/w500/jm4CYBED9I5e8C...,불안,6.0,6.75
96,217,수퍼 소닉 3,"너클즈, 테일즈와 함께 평화로운 일상을 보내던 초특급 히어로 소닉. 연구 시설에 5...",https://image.tmdb.org/t/p/w500/4784u4fHwcvc4o...,기쁨,1.0,7.67
97,218,어카운턴트 2,크리스찬 울프는 복잡한 문제를 해결하는 데 재능이 있다. 오랜 지인이 ‘회계사를 찾...,https://image.tmdb.org/t/p/w500/625ohbmqK8tj9D...,분노,2.0,7.15
98,219,클라운 인 어 콘필드,한적한 시골 마을 킬리 조지. 신입생 퀸과 친구들은 이상하게 퍼져가는 폭력의 기운을...,https://image.tmdb.org/t/p/w500/ovv0uYF2rwhDe1...,분노,2.0,6.20
99,220,Abraham's Boys,Max and Rudy Van Helsing have spent their live...,https://image.tmdb.org/t/p/w500/e10AbPwcJk5b7j...,상처,4.0,5.47

In [3]:
view_df = df[['title', 'overview', 'emotion', 'emotion_num']]
view_df

,title,overview,emotion,emotion_num
0,우주전쟁,전설적인 동명 소설을 새롭게 재해석한 이번 작품은 거대한 침공의 서막을 알린다. 에...,기쁨,1.0
1,F1 더 무비,한때 주목받는 유망주였지만 끔찍한 사고로 F1®에서 우승하지 못하고 한순간에 추락한...,불안,6.0
2,슈퍼맨,"슈퍼맨은 오늘도 세계 곳곳의 위협에 맞서 싸우지만, 시민들의 반응은 극과 극으로 갈...",불안,6.0
3,미션 임파서블: 파이널 레코닝,디지털상의 모든 정보를 통제할 수 있는 사상 초유의 무기로 인해 전 세계 국가와 조...,불안,1.0
4,이니 미니,20세기 스튜디오에서 선사하는 ⟪이니 미니⟫는 십 대 시절 도주 운전을 맡았던 주인...,슬픔,3.0
...,...,...,...,...
95,Sorority,A tale of seduction and mystery. A fearless pr...,불안,6.0
96,수퍼 소닉 3,"너클즈, 테일즈와 함께 평화로운 일상을 보내던 초특급 히어로 소닉. 연구 시설에 5...",기쁨,1.0
97,어카운턴트 2,크리스찬 울프는 복잡한 문제를 해결하는 데 재능이 있다. 오랜 지인이 ‘회계사를 찾...,분노,2.0
98,클라운 인 어 콘필드,한적한 시골 마을 킬리 조지. 신입생 퀸과 친구들은 이상하게 퍼져가는 폭력의 기운을...,분노,2.0
99,Abraham's Boys,Max and Rudy Van Helsing have spent their live...,상처,4.0

In [4]:
df["emotion"].value_counts()

emotion
불안    22
분노    20
기쁨    18
슬픔    14
당황    13
상처    13
Name: count, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   movie_id     100 non-null    int64
 1   title        100 non-null    object
 2   overview     100 non-null    object
 3   poster_url   100 non-null    object
 4   emotion      100 non-null    object
 5   emotion_num  100 non-null    float64
 6   rating       100 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB